export { App } from "./App";
export { Dashboard } from "./Dashboard";
export { FAQ } from "./FAQ";
export { Home } from "./Home";
export { Login } from "./Login";
export { SetupAccount } from "./SetupAccount";
export { SignUp } from "./SignUp";
export { VerifyAccount } from "./VerifyAccount";
export { ConfirmAccount } from "./ConfirmAccount";
